<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tmcolor</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>tmcolor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment.line.double-slash</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.double-dash</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.number-sign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.percentage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.character</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.block.documentation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.character</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.language</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^comment.*</string>
			<key>name</key>
			<string>comment.tmcolor</string>
		</dict>
		<key>comment.line</key>
		<dict>
			<key>match</key>
			<string>^comment\.line.*</string>
			<key>name</key>
			<string>comment.line.tmcolor</string>
		</dict>
		<key>comment.line.double-slash</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.double-slash.*</string>
			<key>name</key>
			<string>comment.line.double-slash.tmcolor</string>
		</dict>
		<key>comment.line.double-dash</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.double-dash.*</string>
			<key>name</key>
			<string>comment.line.double-dash.tmcolor</string>
		</dict>
		<key>comment.line.number-sign</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.number-sign.*</string>
			<key>name</key>
			<string>comment.line.number-sign.tmcolor</string>
		</dict>
		<key>comment.line.percentage</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.percentage.*</string>
			<key>name</key>
			<string>comment.line.percentage.tmcolor</string>
		</dict>
		<key>comment.line.character</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.character.*</string>
			<key>name</key>
			<string>comment.line.character.tmcolor</string>
		</dict>
		<key>comment.block</key>
		<dict>
			<key>match</key>
			<string>^comment\.block.*</string>
			<key>name</key>
			<string>comment.block.tmcolor</string>
		</dict>
		<key>comment.block.documentation</key>
		<dict>
			<key>match</key>
			<string>^comment\.block\.documentation.*</string>
			<key>name</key>
			<string>comment.block.documentation.tmcolor</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>^constant.*</string>
			<key>name</key>
			<string>constant.tmcolor</string>
		</dict>
		<key>constant.numeric</key>
		<dict>
			<key>match</key>
			<string>^constant\.numeric.*</string>
			<key>name</key>
			<string>constant.numeric.tmcolor</string>
		</dict>
		<key>constant.character</key>
		<dict>
			<key>match</key>
			<string>^constant\.character.*</string>
			<key>name</key>
			<string>constant.character.tmcolor</string>
		</dict>
		<key>constant.escape</key>
		<dict>
			<key>match</key>
			<string>^constant\.escape.*</string>
			<key>name</key>
			<string>constant.escape.tmcolor</string>
		</dict>
		<key>constant.language</key>
		<dict>
			<key>match</key>
			<string>^constant\.language.*</string>
			<key>name</key>
			<string>constant.language.tmcolor</string>
		</dict>
		<key>constant.other</key>
		<dict>
			<key>match</key>
			<string>^constant\.other.*</string>
			<key>name</key>
			<string>constant.other.tmcolor</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tmcolor</string>
	<key>uuid</key>
	<string>F01F22AC-7CAA-11D9-9B10-000A95E13C98</string>
</dict>
</plist>
