<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tmcolor</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>tmcolor</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment.line.double-slash</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.double-dash</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.number-sign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.percentage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line.character</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.block.documentation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment.block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.character</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.language</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.name.function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.name.type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.name.tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.name.section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.other.inherited-class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.other.attribute-name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid.illegal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid.deprecated</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword.control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword.control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword.control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.bold</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.heading</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.italic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.list.numbered</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.list.unnumbered</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.list</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.underline.link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.underline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.quote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.raw</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#markup</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#meta</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage.type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage.modifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.quoted.single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.quoted.double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.quoted.triple</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.quoted.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.quoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.unquoted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.interpolated</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.regexp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.constant</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable.parameter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable.language</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable.other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^comment.*</string>
			<key>name</key>
			<string>comment.tmcolor</string>
		</dict>
		<key>comment.line</key>
		<dict>
			<key>match</key>
			<string>^comment\.line.*</string>
			<key>name</key>
			<string>comment.line.tmcolor</string>
		</dict>
		<key>comment.line.double-slash</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.double-slash.*</string>
			<key>name</key>
			<string>comment.line.double-slash.tmcolor</string>
		</dict>
		<key>comment.line.double-dash</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.double-dash.*</string>
			<key>name</key>
			<string>comment.line.double-dash.tmcolor</string>
		</dict>
		<key>comment.line.number-sign</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.number-sign.*</string>
			<key>name</key>
			<string>comment.line.number-sign.tmcolor</string>
		</dict>
		<key>comment.line.percentage</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.percentage.*</string>
			<key>name</key>
			<string>comment.line.percentage.tmcolor</string>
		</dict>
		<key>comment.line.character</key>
		<dict>
			<key>match</key>
			<string>^comment\.line\.character.*</string>
			<key>name</key>
			<string>comment.line.character.tmcolor</string>
		</dict>
		<key>comment.block</key>
		<dict>
			<key>match</key>
			<string>^comment\.block.*</string>
			<key>name</key>
			<string>comment.block.tmcolor</string>
		</dict>
		<key>comment.block.documentation</key>
		<dict>
			<key>match</key>
			<string>^comment\.block\.documentation.*</string>
			<key>name</key>
			<string>comment.block.documentation.tmcolor</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>^constant.*</string>
			<key>name</key>
			<string>constant.tmcolor</string>
		</dict>
		<key>constant.numeric</key>
		<dict>
			<key>match</key>
			<string>^constant\.numeric.*</string>
			<key>name</key>
			<string>constant.numeric.tmcolor</string>
		</dict>
		<key>constant.character</key>
		<dict>
			<key>match</key>
			<string>^constant\.character.*</string>
			<key>name</key>
			<string>constant.character.tmcolor</string>
		</dict>
		<key>constant.escape</key>
		<dict>
			<key>match</key>
			<string>^constant\.escape.*</string>
			<key>name</key>
			<string>constant.escape.tmcolor</string>
		</dict>
		<key>constant.language</key>
		<dict>
			<key>match</key>
			<string>^constant\.language.*</string>
			<key>name</key>
			<string>constant.language.tmcolor</string>
		</dict>
		<key>constant.other</key>
		<dict>
			<key>match</key>
			<string>^constant\.other.*</string>
			<key>name</key>
			<string>constant.other.tmcolor</string>
		</dict>
		<key>entity</key>
		<dict>
			<key>match</key>
			<string>^entity.*</string>
			<key>name</key>
			<string>entity.tmcolor</string>
		</dict>
		<key>entity.name</key>
		<dict>
			<key>match</key>
			<string>^entity\.name.*</string>
			<key>name</key>
			<string>entity.name.tmcolor</string>
		</dict>
		<key>entity.name.function</key>
		<dict>
			<key>match</key>
			<string>^entity\.name\.function.*</string>
			<key>name</key>
			<string>entity.name.function.tmcolor</string>
		</dict>
		<key>entity.name.type</key>
		<dict>
			<key>match</key>
			<string>^entity\.name\.type.*</string>
			<key>name</key>
			<string>entity.name.type.tmcolor</string>
		</dict>
		<key>entity.name.tag</key>
		<dict>
			<key>match</key>
			<string>^entity\.name\.tag.*</string>
			<key>name</key>
			<string>entity.name.tag.tmcolor</string>
		</dict>
		<key>entity.name.section</key>
		<dict>
			<key>match</key>
			<string>^entity\.name\.section.*</string>
			<key>name</key>
			<string>entity.name.section.tmcolor</string>
		</dict>
		<key>entity.other</key>
		<dict>
			<key>match</key>
			<string>^entity\.other.*</string>
			<key>name</key>
			<string>entity.other.tmcolor</string>
		</dict>
		<key>entity.other.inherited-class</key>
		<dict>
			<key>match</key>
			<string>^entity\.other\.inherited-class.*</string>
			<key>name</key>
			<string>entity.other.inherited-class.tmcolor</string>
		</dict>
		<key>entity.other.attribute-name</key>
		<dict>
			<key>match</key>
			<string>^entity\.other\.attribute-name.*</string>
			<key>name</key>
			<string>entity.other.attribute-name.tmcolor</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>^invalid.*</string>
			<key>name</key>
			<string>invalid.tmcolor</string>
		</dict>
		<key>invalid.illegal</key>
		<dict>
			<key>match</key>
			<string>^invalid\.illegal.*</string>
			<key>name</key>
			<string>invalid.illegal.tmcolor</string>
		</dict>
		<key>invalid.deprecated</key>
		<dict>
			<key>match</key>
			<string>^invalid\.deprecated.*</string>
			<key>name</key>
			<string>invalid.deprecated.tmcolor</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>^keyword.*</string>
			<key>name</key>
			<string>keyword.tmcolor</string>
		</dict>
		<key>keyword.control</key>
		<dict>
			<key>match</key>
			<string>^keyword\.control.*</string>
			<key>name</key>
			<string>keyword.control.tmcolor</string>
		</dict>
		<key>keyword.operator</key>
		<dict>
			<key>match</key>
			<string>^keyword\.operator.*</string>
			<key>name</key>
			<string>keyword.operator.tmcolor</string>
		</dict>
		<key>keyword.other</key>
		<dict>
			<key>match</key>
			<string>^keyword\.other.*</string>
			<key>name</key>
			<string>keyword.other.tmcolor</string>
		</dict>
		<key>markup</key>
		<dict>
			<key>match</key>
			<string>^markup.*</string>
			<key>name</key>
			<string>markup.tmcolor</string>
		</dict>
		<key>markup.underline</key>
		<dict>
			<key>match</key>
			<string>^markup\.underline.*</string>
			<key>name</key>
			<string>markup.underline.tmcolor</string>
		</dict>
		<key>markup.underline.link</key>
		<dict>
			<key>match</key>
			<string>^markup\.underline\.link.*</string>
			<key>name</key>
			<string>markup.underline.link.tmcolor</string>
		</dict>
		<key>markup.bold</key>
		<dict>
			<key>match</key>
			<string>^markup\.bold.*</string>
			<key>name</key>
			<string>markup.bold.tmcolor</string>
		</dict>
		<key>markup.heading</key>
		<dict>
			<key>match</key>
			<string>^markup\.heading.*</string>
			<key>name</key>
			<string>markup.heading.tmcolor</string>
		</dict>
		<key>markup.italic</key>
		<dict>
			<key>match</key>
			<string>^markup\.italic.*</string>
			<key>name</key>
			<string>markup.italic.tmcolor</string>
		</dict>
		<key>markup.list</key>
		<dict>
			<key>match</key>
			<string>^markup\.list.*</string>
			<key>name</key>
			<string>markup.list.tmcolor</string>
		</dict>
		<key>markup.list.numbered</key>
		<dict>
			<key>match</key>
			<string>^markup\.list\.numbered.*</string>
			<key>name</key>
			<string>markup.list.numbered.tmcolor</string>
		</dict>
		<key>markup.list.unnumbered</key>
		<dict>
			<key>match</key>
			<string>^markup\.list\.unnumbered.*</string>
			<key>name</key>
			<string>markup.list.unnumbered.tmcolor</string>
		</dict>
		<key>markup.quote</key>
		<dict>
			<key>match</key>
			<string>^markup\.quote.*</string>
			<key>name</key>
			<string>markup.quote.tmcolor</string>
		</dict>
		<key>markup.raw</key>
		<dict>
			<key>match</key>
			<string>^markup\.raw.*</string>
			<key>name</key>
			<string>markup.raw.tmcolor</string>
		</dict>
		<key>markup.other</key>
		<dict>
			<key>match</key>
			<string>^markup\.other.*</string>
			<key>name</key>
			<string>markup.other.tmcolor</string>
		</dict>
		<key>meta</key>
		<dict>
			<key>match</key>
			<string>^meta.*</string>
			<key>name</key>
			<string>meta.tmcolor</string>
		</dict>
		<key>storage</key>
		<dict>
			<key>match</key>
			<string>^storage.*</string>
			<key>name</key>
			<string>storage.tmcolor</string>
		</dict>
		<key>storage.type</key>
		<dict>
			<key>match</key>
			<string>^storage\.type.*</string>
			<key>name</key>
			<string>storage.type.tmcolor</string>
		</dict>
		<key>storage.modifier</key>
		<dict>
			<key>match</key>
			<string>^storage\.modifier.*</string>
			<key>name</key>
			<string>storage.modifier.tmcolor</string>
		</dict>
		<key>string</key>
		<dict>
			<key>match</key>
			<string>^string.*</string>
			<key>name</key>
			<string>string.tmcolor</string>
		</dict>
		<key>string.quoted</key>
		<dict>
			<key>match</key>
			<string>^string\.quoted.*</string>
			<key>name</key>
			<string>string.quoted.tmcolor</string>
		</dict>
		<key>string.quoted.single </key>
		<dict>
			<key>match</key>
			<string>^string\.quoted\.single .*</string>
			<key>name</key>
			<string>string.quoted.single .tmcolor</string>
		</dict>
		<key>string.quoted.double </key>
		<dict>
			<key>match</key>
			<string>^string\.quoted\.double .*</string>
			<key>name</key>
			<string>string.quoted.double .tmcolor</string>
		</dict>
		<key>string.quoted.triple </key>
		<dict>
			<key>match</key>
			<string>^string\.quoted\.triple .*</string>
			<key>name</key>
			<string>string.quoted.triple .tmcolor</string>
		</dict>
		<key>string.quoted.other </key>
		<dict>
			<key>match</key>
			<string>^string\.quoted\.other .*</string>
			<key>name</key>
			<string>string.quoted.other .tmcolor</string>
		</dict>
		<key>string.unquoted</key>
		<dict>
			<key>match</key>
			<string>^string\.unquoted.*</string>
			<key>name</key>
			<string>string.unquoted.tmcolor</string>
		</dict>
		<key>string.interpolated</key>
		<dict>
			<key>match</key>
			<string>^string\.interpolated.*</string>
			<key>name</key>
			<string>string.interpolated.tmcolor</string>
		</dict>
		<key>string.regexp</key>
		<dict>
			<key>match</key>
			<string>^string\.regexp.*</string>
			<key>name</key>
			<string>string.regexp.tmcolor</string>
		</dict>
		<key>string.other</key>
		<dict>
			<key>match</key>
			<string>^string\.other.*</string>
			<key>name</key>
			<string>string.other.tmcolor</string>
		</dict>
		<key>support</key>
		<dict>
			<key>match</key>
			<string>^support.*</string>
			<key>name</key>
			<string>support.tmcolor</string>
		</dict>
		<key>support.function</key>
		<dict>
			<key>match</key>
			<string>^support\.function.*</string>
			<key>name</key>
			<string>support.function.tmcolor</string>
		</dict>
		<key>support.class</key>
		<dict>
			<key>match</key>
			<string>^support\.class.*</string>
			<key>name</key>
			<string>support.class.tmcolor</string>
		</dict>
		<key>support.type</key>
		<dict>
			<key>match</key>
			<string>^support\.type.*</string>
			<key>name</key>
			<string>support.type.tmcolor</string>
		</dict>
		<key>support.constant</key>
		<dict>
			<key>match</key>
			<string>^support\.constant.*</string>
			<key>name</key>
			<string>support.constant.tmcolor</string>
		</dict>
		<key>support.variable</key>
		<dict>
			<key>match</key>
			<string>^support\.variable.*</string>
			<key>name</key>
			<string>support.variable.tmcolor</string>
		</dict>
		<key>support.other</key>
		<dict>
			<key>match</key>
			<string>^support\.other.*</string>
			<key>name</key>
			<string>support.other.tmcolor</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>^variable.*</string>
			<key>name</key>
			<string>variable.tmcolor</string>
		</dict>
		<key>variable.parameter</key>
		<dict>
			<key>match</key>
			<string>^variable\.parameter.*</string>
			<key>name</key>
			<string>variable.parameter.tmcolor</string>
		</dict>
		<key>variable.language</key>
		<dict>
			<key>match</key>
			<string>^variable\.language.*</string>
			<key>name</key>
			<string>variable.language.tmcolor</string>
		</dict>
		<key>variable.other</key>
		<dict>
			<key>match</key>
			<string>^variable\.other.*</string>
			<key>name</key>
			<string>variable.other.tmcolor</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tmcolor</string>
	<key>uuid</key>
	<string>F01F22AC-7CAA-11D9-9B10-000A95E13C98</string>
</dict>
</plist>
